In [1]:
#importing libraries
import pandas as pd
import pickle
import numpy as np

In [2]:
#loading the dataset which is saved.
loaded_data = np.load("dataset_file.npy")

In [3]:
loaded_data

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 1.9226183e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.9179206e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.9105039e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 1.8290199e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.6618794e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 1.5699112e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 1.5612251e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.5575260e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 1.5221177e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.2333488e+05, 1.0867917e+05,

In [4]:
# Load the training data
with open('train_data.pkl', 'rb') as file:
    X_train_loaded, y_train_loaded = pickle.load(file)

# Load the testing data
with open('test_data.pkl', 'rb') as file:
    X_test_loaded, y_test_loaded = pickle.load(file)

In [5]:
#loading the saved standaradscaler function
from joblib import load
loaded_scaler = load('standarad_scaler.joblib')

In [6]:
loaded_scaler

StandardScaler()

In [7]:
#loading transformed standaradscaler from test set
transformed_data = loaded_scaler.transform(X_test_loaded)

In [8]:
#printing the convertion of raw input to 
#standaradscaler form(preprocessed state)
transformed_data

array([[-0.07603728,  2.36704999, -0.58361684,  2.36643191, -0.80622577],
       [ 0.63847282, -1.18525561,  0.41167846, -0.42257713, -0.80622577],
       [ 0.66408753, -0.4500642 ,  0.25599967,  2.36643191, -0.80622577],
       [-0.86356929, -1.46206777, -0.2332684 ,  2.36643191, -0.80622577],
       [ 1.7275513 , -0.81949011,  1.60810794,  2.36643191, -0.80622577],
       [ 0.04895046,  0.22518663,  1.19401482, -0.42257713,  1.24034735],
       [-1.02172808, -2.19566942, -0.07599535, -0.42257713,  1.24034735],
       [-0.17747785,  1.19629418, -0.8099845 , -0.42257713,  1.24034735],
       [ 0.08789427,  0.02649513,  0.81687706,  2.36643191, -0.80622577],
       [ 1.49363229, -1.20084971,  1.29222059,  2.36643191, -0.80622577],
       [-0.29392851, -0.74473584,  0.14613493,  2.36643191, -0.80622577],
       [-0.48957899, -1.44890443,  0.07717955, -0.42257713,  1.24034735],
       [ 0.11543228,  0.86137752, -0.46334712,  2.36643191, -0.80622577],
       [-0.48107494,  1.39147463,  0.1

In [9]:
#converting the Raw_input to pre_processed input using python code
preproc_input= loaded_scaler.transform([[13000,12000,4000,0,1]])

/home/had/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [10]:
#Converting the user input to preprocessed input
preproc_input

array([[-1.17093516, -4.30496048, -1.44694752, -0.42257713,  1.24034735]])

In [11]:
#loading the saved model & predicting the preprocessed input
loaded_model=pickle.load(open("bestmodel_svm_preinput.sav","rb"))
result = loaded_model.predict(preproc_input)

In [12]:
#output in Raw state(human understandable form)
result

array([107181.20623513])

In [13]:
#giving Dyanmic input
dy_rnd = float(input("Enter RND value:"))
dy_admin =float(input("Enter admin value:"))
dy_markspnd =float(input("Enter the marketspend:"))
dy_florida = int(input("Enter the value 0 or 1:"))
dy_newyork = int(input("Enter the value 0 or 1:"))


Enter RND value:13000
Enter admin value:12000
Enter the marketspend:4000
Enter the value 0 or 1:1
Enter the value 0 or 1:0


In [14]:
dyn_inp_result =loaded_model.predict(loaded_scaler.transform([[dy_rnd,dy_admin,dy_markspnd,dy_florida,dy_newyork]]))

/home/had/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [15]:
#output in raw state.
dyn_inp_result

array([107861.0302793])