In [1]:
!pip install lightgbm==3.3.5

In [2]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import lightgbm as lgb

In [3]:
#dataset reading
dts = pd.read_csv("insurance_pre.csv")

In [4]:
dts

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dts.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [6]:
dts = pd.get_dummies(dts,drop_first=True)

In [7]:
dts

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
#columns rename-ing
dts.rename(columns={"sex_male":"sex","smoker_yes":"smoker"},inplace=True)

In [9]:
dts

age     bmi  children      charges  sex  smoker
0      19  27.900         0  16884.92400    0       1
1      18  33.770         1   1725.55230    1       0
2      28  33.000         3   4449.46200    1       0
3      33  22.705         0  21984.47061    1       0
4      32  28.880         0   3866.85520    1       0
...   ...     ...       ...          ...  ...     ...
1333   50  30.970         3  10600.54830    1       0
1334   18  31.920         0   2205.98080    0       0
1335   18  36.850         0   1629.83350    0       0
1336   21  25.800         0   2007.94500    0       0
1337   61  29.070         0  29141.36030    0       1

[1338 rows x 6 columns]

In [10]:
#separate the input and output values
feature = dts[["age","bmi","children","sex","smoker"]]
target = dts[["charges"]]

In [11]:
feature,target

(      age     bmi  children  sex  smoker
 0      19  27.900         0    0       1
 1      18  33.770         1    1       0
 2      28  33.000         3    1       0
 3      33  22.705         0    1       0
 4      32  28.880         0    1       0
 ...   ...     ...       ...  ...     ...
 1333   50  30.970         3    1       0
 1334   18  31.920         0    0       0
 1335   18  36.850         0    0       0
 1336   21  25.800         0    0       0
 1337   61  29.070         0    0       1
 
 [1338 rows x 5 columns],
           charges
 0     16884.92400
 1      1725.55230
 2      4449.46200
 3     21984.47061
 4      3866.85520
 ...           ...
 1333  10600.54830
 1334   2205.98080
 1335   1629.83350
 1336   2007.94500
 1337  29141.36030
 
 [1338 rows x 1 columns])

In [12]:
#splitting the train & test sets.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(feature,target,test_size=0.33,random_state=0)

In [13]:
X_train, X_test

(      age     bmi  children  sex  smoker
 1271   25  34.485         0    0       0
 1313   19  34.700         2    0       1
 2      28  33.000         3    1       0
 405    52  38.380         2    0       0
 482    18  31.350         0    0       0
 ...   ...     ...       ...  ...     ...
 763    27  26.030         0    1       0
 835    42  35.970         2    1       0
 1216   40  25.080         0    1       0
 559    19  35.530         0    1       0
 684    33  18.500         1    0       0
 
 [896 rows x 5 columns],
       age     bmi  children  sex  smoker
 578    52  30.200         1    1       0
 610    47  29.370         1    0       0
 569    48  40.565         2    1       1
 1034   61  38.380         0    1       0
 198    51  18.050         0    0       0
 ...   ...     ...       ...  ...     ...
 117    29  27.940         1    0       1
 520    50  27.360         0    0       0
 422    40  32.775         1    1       1
 294    25  26.800         3    1       0
 261   

In [14]:
Y_train, Y_test

(          charges
 1271   3021.80915
 1313  36397.57600
 2      4449.46200
 405   11396.90020
 482    1622.18850
 ...           ...
 763    3070.80870
 835    7160.33030
 1216   5415.66120
 559    1646.42970
 684    4766.02200
 
 [896 rows x 1 columns],
           charges
 578    9724.53000
 610    8547.69130
 569   45702.02235
 1034  12950.07120
 198    9644.25250
 ...           ...
 117   19107.77960
 520   25656.57526
 422   39125.33225
 294    3906.12700
 261   17085.26760
 
 [442 rows x 1 columns])

In [15]:
#Standardisation procedure to maintain least different between inputs.
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
X_train

array([[-1.03606235,  0.6150522 , -0.91008919, -0.98669564, -0.4996512 ],
       [-1.46484381,  0.64987934,  0.7540739 , -0.98669564,  2.00139616],
       [-0.82167162,  0.37450199,  1.58615545,  1.01348375, -0.4996512 ],
       ...,
       [ 0.03589131, -0.90843249, -0.91008919,  1.01348375, -0.4996512 ],
       [-1.46484381,  0.78432828, -0.91008919,  1.01348375, -0.4996512 ],
       [-0.46435373, -1.97430482, -0.07800765, -0.98669564, -0.4996512 ]])

In [17]:
X_test

array([[ 0.89345423, -0.07906071, -0.07800765,  1.01348375, -0.4996512 ],
       [ 0.53613634, -0.21350965, -0.07800765, -0.98669564, -0.4996512 ],
       [ 0.60759992,  1.59993119,  0.7540739 ,  1.01348375,  2.00139616],
       ...,
       [ 0.03589131,  0.33805498, -0.07800765,  1.01348375,  2.00139616],
       [-1.03606235, -0.62981541,  1.58615545,  1.01348375, -0.4996512 ],
       [-1.39338023, -0.62333594, -0.07800765, -0.98669564,  2.00139616]])

In [18]:
#Creating & training the model
from lightgbm import LGBMRegressor
model1_create = LGBMRegressor(objective = "regression", boosting_type = "gbdt",num_leaves = 31,max_depth = 3,n_estimators=110,learning_rate = 0.05,feature_fraction = 0.9)
model1_create = model1_create.fit(X_train, Y_train)

[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9


/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
Y_pred1 = model1_create.predict(X_test)

In [20]:
Y_pred1

array([13054.93783965, 10507.80522485, 46020.71009528, 14352.9395881 ,
        9774.2568443 ,  4662.4522464 ,  2735.31171196, 12163.691754  ,
        7470.61834653,  6820.29750827,  6673.75501136, 12018.1203353 ,
        9929.62536957,  6178.33640181, 19923.4796009 , 12191.62345205,
       14899.84342778,  5491.22123383,  7340.29827944, 34301.6379214 ,
       24502.42462892, 14277.50426714, 12177.10298542, 26471.16809889,
        3585.43991161,  6434.97780415,  4455.01478593,  8121.8769662 ,
        5016.68602314, 10216.32379074,  7980.70792812, 48632.32522574,
       14643.34760921, 11855.72546094, 17105.08213524,  5235.8269401 ,
       10821.57976743, 37077.95873006, 39048.07620907,  3611.86610082,
        5381.45676275,  5320.00315659, 20382.21198973, 47451.4029436 ,
       37118.68982859,  4888.85096826, 12191.62345205,  7590.45718683,
        5603.46589453, 12574.03397505,  4634.88943553,  4469.06532437,
       26482.01706988, 46760.13818429, 11844.91340398,  5330.36082116,
      

In [21]:
from sklearn.metrics import r2_score
rscore1 = r2_score(Y_test,Y_pred1)


In [22]:
#model1
rscore1

0.8967952442781606

In [23]:
#saving model phase
import pickle
filename = "bestmodel_LightGBM.sav"
pickle.dump(model1_create,open(filename,"wb"))

In [30]:
#loading the model for testing purpose
#Giving static input
loaded_model = pickle.load(open("bestmodel_LightGBM.sav","rb"))
static_input = loaded_model.predict([[61,29.070,0,0,1]])

In [31]:
#actual output 29141.360, Predicted output 49973.44
static_input

array([49973.44886376])

In [26]:
#Giving Dynamic input
dy_age =  int(input("Enter the age:"))
dy_bmi = float(input("Enter the bmi:"))
dy_childrens = int(input("Enter no of childrens:"))
dy_gender = int(input("Enter the gender 0 or 1:"))
dy_smoker = int(input("Enter the smoker 0 or 1:"))

Enter the age:61
Enter the bmi:29.070
Enter no of childrens:0
Enter the gender 0 or 1:0
Enter the smoker 0 or 1:1


In [28]:
dynamic_input = loaded_model.predict([[dy_age,dy_bmi,dy_childrens,dy_gender,dy_smoker]])

In [29]:
#actual output 29141.360, Predicted output 49973.44
dynamic_input

array([49973.44886376])