In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#Storing the .CSV information into a variable
dts = pd.read_csv("insurance_pre.csv")

In [3]:
dts

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#viewing the total no of columns
dts.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [5]:
dts = pd.get_dummies(dts)

In [6]:
dts

age     bmi  children      charges  sex_female  sex_male  smoker_no  \
0      19  27.900         0  16884.92400           1         0          0   
1      18  33.770         1   1725.55230           0         1          1   
2      28  33.000         3   4449.46200           0         1          1   
3      33  22.705         0  21984.47061           0         1          1   
4      32  28.880         0   3866.85520           0         1          1   
...   ...     ...       ...          ...         ...       ...        ...   
1333   50  30.970         3  10600.54830           0         1          1   
1334   18  31.920         0   2205.98080           1         0          1   
1335   18  36.850         0   1629.83350           1         0          1   
1336   21  25.800         0   2007.94500           1         0          1   
1337   61  29.070         0  29141.36030           1         0          0   

      smoker_yes  
0              1  
1              0  
2              0  
3              0  
4              0  
...          ...  
1333           0  
1334           0  
1335           0  
1336           0  
1337           1  

[1338 rows x 8 columns]

In [7]:
feature = dts[["age","bmi","children","sex_female","sex_male","smoker_yes","smoker_no"]]
feature

age     bmi  children  sex_female  sex_male  smoker_yes  smoker_no
0      19  27.900         0           1         0           1          0
1      18  33.770         1           0         1           0          1
2      28  33.000         3           0         1           0          1
3      33  22.705         0           0         1           0          1
4      32  28.880         0           0         1           0          1
...   ...     ...       ...         ...       ...         ...        ...
1333   50  30.970         3           0         1           0          1
1334   18  31.920         0           1         0           0          1
1335   18  36.850         0           1         0           0          1
1336   21  25.800         0           1         0           0          1
1337   61  29.070         0           1         0           1          0

[1338 rows x 7 columns]

In [8]:
target = dts[["charges"]]
target

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
#splitting the train & test dataset.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(feature,target,test_size=0.33,random_state=0)

In [10]:
#Printing training dataset
X_train, Y_train

(      age     bmi  children  sex_female  sex_male  smoker_yes  smoker_no
 1271   25  34.485         0           1         0           0          1
 1313   19  34.700         2           1         0           1          0
 2      28  33.000         3           0         1           0          1
 405    52  38.380         2           1         0           0          1
 482    18  31.350         0           1         0           0          1
 ...   ...     ...       ...         ...       ...         ...        ...
 763    27  26.030         0           0         1           0          1
 835    42  35.970         2           0         1           0          1
 1216   40  25.080         0           0         1           0          1
 559    19  35.530         0           0         1           0          1
 684    33  18.500         1           1         0           0          1
 
 [896 rows x 7 columns],
           charges
 1271   3021.80915
 1313  36397.57600
 2      4449.46200
 405   11

In [11]:
#Printing testing dataset.
Y_train, Y_test

(          charges
 1271   3021.80915
 1313  36397.57600
 2      4449.46200
 405   11396.90020
 482    1622.18850
 ...           ...
 763    3070.80870
 835    7160.33030
 1216   5415.66120
 559    1646.42970
 684    4766.02200
 
 [896 rows x 1 columns],
           charges
 578    9724.53000
 610    8547.69130
 569   45702.02235
 1034  12950.07120
 198    9644.25250
 ...           ...
 117   19107.77960
 520   25656.57526
 422   39125.33225
 294    3906.12700
 261   17085.26760
 
 [442 rows x 1 columns])

In [21]:
X_train

age     bmi  children  sex_female  sex_male  smoker_yes  smoker_no
1271   25  34.485         0           1         0           0          1
1313   19  34.700         2           1         0           1          0
2      28  33.000         3           0         1           0          1
405    52  38.380         2           1         0           0          1
482    18  31.350         0           1         0           0          1
...   ...     ...       ...         ...       ...         ...        ...
763    27  26.030         0           0         1           0          1
835    42  35.970         2           0         1           0          1
1216   40  25.080         0           0         1           0          1
559    19  35.530         0           0         1           0          1
684    33  18.500         1           1         0           0          1

[896 rows x 7 columns]

In [22]:
#Standardisation procedure to maintain least different between inputs.
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [25]:
print(X_train)

[[-1.03606235  0.6150522  -0.91008919 ... -0.98669564 -0.4996512
   0.4996512 ]
 [-1.46484381  0.64987934  0.7540739  ... -0.98669564  2.00139616
  -2.00139616]
 [-0.82167162  0.37450199  1.58615545 ...  1.01348375 -0.4996512
   0.4996512 ]
 ...
 [ 0.03589131 -0.90843249 -0.91008919 ...  1.01348375 -0.4996512
   0.4996512 ]
 [-1.46484381  0.78432828 -0.91008919 ...  1.01348375 -0.4996512
   0.4996512 ]
 [-0.46435373 -1.97430482 -0.07800765 ... -0.98669564 -0.4996512
   0.4996512 ]]


In [26]:
print(X_test)

[[ 0.89345423 -0.07906071 -0.07800765 ...  1.01348375 -0.4996512
   0.4996512 ]
 [ 0.53613634 -0.21350965 -0.07800765 ... -0.98669564 -0.4996512
   0.4996512 ]
 [ 0.60759992  1.59993119  0.7540739  ...  1.01348375  2.00139616
  -2.00139616]
 ...
 [ 0.03589131  0.33805498 -0.07800765 ...  1.01348375  2.00139616
  -2.00139616]
 [-1.03606235 -0.62981541  1.58615545 ...  1.01348375 -0.4996512
   0.4996512 ]
 [-1.39338023 -0.62333594 -0.07800765 ... -0.98669564  2.00139616
  -2.00139616]]


In [174]:
#Model creation and training
from sklearn.svm import SVR
model_create = SVR(kernel = "sigmoid", C=10)
model_create.fit(X_train, Y_train)

/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=10, kernel='sigmoid')

In [175]:
#checking the values of slope 'm' and bias 'c' values
#'coef_' can be used when kernel = "linear" 
#otherwise showing AttributeError: coef_ is only available when using a linear kernel
#'intercept_' should be used when kernel = "rbf" (radial bias/Intercept factor)
bias =  model_create.intercept_
bias

array([9655.99248727])

In [176]:
slope = model_create.n_support_
slope

array([896], dtype=int32)

In [177]:
#support vector datapoints count.
model_create.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [178]:
Y_pred = model_create.predict(X_test)

In [179]:
#Evaluation metric phase
from sklearn.metrics import r2_score
rscore= r2_score(Y_test,Y_pred)

In [180]:
rscore

0.05297788955343086